name: Docker

on:
  workflow_dispatch:
  push:
    paths:
      - '**/.github/workflows/docker.yml'
      - '**/Dockerfile.fortest'

jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: [self-hosted, x64]
    container:
      image: ubuntu-20.04
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build and push
      run: |
        make docker
    - name: Invoke test workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Go
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
