name: Docker

on:
  workflow_dispatch:
  push:
    paths:
      - '**/.github/workflows/docker.yml'
      - '**/Dockerfile.fortest'

jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: [self-hosted, x64]
    container:
      image: ubuntu:20.04
    steps:
    - name: base setup
      run: |
        apt-get update
        apt install -y ca-certificates curl gpg lsb-release sudo
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build and push
      run: |
        make docker
    - name: Invoke test workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Go
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
